In [14]:
import torch
import time
import copy
import os

if os.path.basename(os.getcwd()) == 'exercises':
    os.chdir('../')
    
from ctm.ctm import ContinuousThoughtMachine

device_config = -1

# Configure device string (support MPS on macOS)
if device_config != -1:
    device = f'cuda:{device_config}'
elif torch.backends.mps.is_available():
    device = 'mps'
else:
    device = 'cpu'
print(f'Running model CTM on {device}')

Running model CTM on cpu


In [ ]:
"""
Basic init for the CTM. More enhanced description is in ctm.py

Mandatory Args:
    iterations = ticks (75 like maze demo)
    d_model = core dimensionality of CTMS's latent space
    n_sync_out = neurons used for output synchronisation 
    n_sync_action = neurons used for action/attention synchronisation 
    synapse_depth = Depth of the synapse model (U-Net if > 1, else MLP)
    memory_length = History length for Neuron-Level Model
    deep_nlms = Deep NLM is better but slower
    memory_hidden_dims = Hidden dimension size for deep NLMs.
    do_layernorm_nlm = Untested in the paper
    backbone_type = Type of feature extraction backbone (e.g., 'resnet18-2', 'none') Maybe insert encoder here
    positional_embedding_type = positional embedding ???
---------
Optional args:
    prediction_reshaper
    dropout
    neuron_select_type
    n_random_pairing_self
"""
#TODO: d_input, heads and out_dims are to be adjusted to the encoding
#TODO: Find out how to inject the encoder and decoder maybe via backbone
#TODO: understand what is the backbone and how is it used
ctm = ContinuousThoughtMachine(iterations=75, 
                               d_model=2048, 
                               d_input=0, 
                               heads=0, 
                               n_synch_out=64, 
                               n_synch_action=32,
                               synapse_depth=8, 
                               memory_length=25, 
                               deep_nlms=False,
                               memory_hidden_dims=32, 
                               do_layernorm_nlm=False,
                               backbone_type='none',
                               positional_embedding_type='none',
                               out_dims=0
                               )
#TODO: Encode a image and decode a Image successfully
#TODO: build a training loop
#TODO: calculate the loss like in the dreamer model example


Using neuron select type: random-pairing
Synch representation size action: 32
Synch representation size out: 64
start_activated_state: Parameter containing:
tensor([-0.0034, -0.0099,  0.0195,  ..., -0.0135, -0.0033,  0.0007],
       requires_grad=True)
start_trace: Parameter containing:
tensor([[-0.0066,  0.0210, -0.0160,  ..., -0.0187, -0.0124,  0.0206],
        [-0.0102, -0.0192,  0.0091,  ..., -0.0152,  0.0021,  0.0004],
        [ 0.0135,  0.0128,  0.0194,  ..., -0.0008, -0.0077, -0.0191],
        ...,
        [ 0.0044,  0.0214, -0.0130,  ..., -0.0011,  0.0096, -0.0158],
        [-0.0182, -0.0057,  0.0068,  ..., -0.0172, -0.0003,  0.0066],
        [-0.0100,  0.0202,  0.0160,  ...,  0.0049, -0.0145, -0.0050]],
       requires_grad=True)
decay_params_action: Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
decay_params_out: Parameter containing:
ten

ValueError: Attempted to use an uninitialized parameter in <function Tensor.__format__ at 0x7e41ea554040>. This error happens when you are using a `LazyModule` or explicitly manipulating `torch.nn.parameter.UninitializedParameter` objects. When using LazyModules Call `forward` with a dummy batch to initialize the parameters before calling torch functions